# Generated by Django 5.2.6 on 2025-09-10 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 10, 13, 27, 11, 791299, tzinfo=datetime.timezone.utc)),
        ),
    ]
