# Generated by Django 5.2.6 on 2025-09-11 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_alter_verificationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 11, 6, 25, 46, 246820, tzinfo=datetime.timezone.utc)),
        ),
    ]
