# Generated by Django 5.2.6 on 2025-09-11 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_alter_verificationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 11, 8, 24, 29, 136739, tzinfo=datetime.timezone.utc)),
        ),
    ]
