# Generated by Django 5.2.6 on 2025-09-12 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0014_alter_verificationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 12, 7, 11, 55, 908974, tzinfo=datetime.timezone.utc)),
        ),
    ]
