# Generated by Django 5.2.6 on 2025-09-12 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0015_alter_verificationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 12, 8, 0, 7, 945650, tzinfo=datetime.timezone.utc)),
        ),
    ]
