# Generated by Django 5.2.6 on 2025-09-15 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0022_alter_verificationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 15, 10, 6, 21, 942465, tzinfo=datetime.timezone.utc)),
        ),
    ]
