# Generated by Django 5.2.6 on 2025-09-15 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0024_alter_verificationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 15, 10, 9, 54, 634498, tzinfo=datetime.timezone.utc)),
        ),
    ]
