# Generated by Django 5.2.6 on 2025-09-15 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0028_alter_verificationcode_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('sales_man', 'Sales Men'), ('admin', 'Admin'), ('dispatcher', 'Dispatcher'), ('delivery_rider', 'Delivery Rider')], default='sales_man', max_length=20),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 15, 12, 1, 40, 726718, tzinfo=datetime.timezone.utc)),
        ),
    ]
