# Generated by Django 5.2.6 on 2025-09-15 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0029_user_last_activity_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 15, 12, 25, 21, 58646, tzinfo=datetime.timezone.utc)),
        ),
    ]
