# Generated by Django 5.2.6 on 2025-09-16 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0031_alter_verificationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 16, 6, 19, 22, 778027, tzinfo=datetime.timezone.utc)),
        ),
    ]
