# Generated by Django 5.2.6 on 2025-09-16 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0033_alter_verificationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 16, 6, 58, 6, 905140, tzinfo=datetime.timezone.utc)),
        ),
    ]
