# Generated by Django 5.2.6 on 2025-09-16 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0035_alter_user_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 16, 9, 11, 13, 199711, tzinfo=datetime.timezone.utc)),
        ),
    ]
