"""
Django settings for plant_mall project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-sh(u7!vngio^=xyn2b_$b^b399+n43w)559)vzv*pigsd2hs^v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'admin_operations',
    'dispatcher',
    "deliveryrider",
    'Authentication',
    'plants_mall_shops',
    'products',
    'orders',
    'rest_framework',
    'corsheaders',
    
]
 


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Authentication.middleware.UpdateLastActivityMiddleware'
]

ROOT_URLCONF = 'plant_mall.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR,"templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'plant_mall.wsgi.application'

AUTH_USER_MODEL = "Authentication.User"
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5174",
    "https://2403af93a8b8.ngrok-free.app",
    "https://theplantsmall-frontend.vercel.app",
    "https://cc816f6f81ad.ngrok-free.app",
    "https://592c665c2db2.ngrok-free.app"
    
 
]

CORS_ALLOW_ALL_ORIGINS = True
 

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

#Jwt configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend"
    ]
    
}
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=4),    
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),      
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

# Folder where collectstatic will collect files for production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Additional locations where Django will look for static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# CLOUDINARY_STORAGE = {
#     'CLOUD_NAME': "dsllytsku",
#     'API_KEY': "445446883233558",
#     'API_SECRET': "o6SMXJbkgYsRoFzR8zGwJOXUPNw"
# }

# DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#smtp config
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'shoaib@northrays.com'
EMAIL_HOST_PASSWORD = 'qgen vfog bxae ornu'
JAZZMIN_SETTINGS = {
    # Branding
    "site_title": "🌱 The Plants Mall Admin",      # Browser tab
    "site_header": "The Plants Mall Dashboard",    # Dashboard top-left
    "site_brand": "The Plants Mall",

    # Logo settings
    "site_logo": "images/logo.png",                # Small logo in header
    "site_logo_classes": "img-circle",             # Rounded logo in header
    "site_icon": "images/logo.png",                # Favicon in browser tab

    # Login page
    "welcome_sign": "Welcome to The Plants Mall Management",
    "login_logo": "images/logo.png",               # Full logo for login screen
    "login_logo_dark": "images/logo.png",          # Optional dark mode version
    "login_title": "The Plants Mall Admin Login",

    # UI tweaks
    "show_sidebar": True,
    "navigation_expanded": True,
    "show_ui_builder": True,

    # Custom CSS to control logo size
    "custom_css": "css/custom_admin.css",
}

