# Generated by Django 5.2.6 on 2025-09-12 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0006_cotton_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cotton',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.cotton'),
        ),
    ]
