# Generated by Django 4.2.7 on 2025-09-25 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_loose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='loose',
        ),
    ]
