# Generated by Django 5.2.6 on 2025-09-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_cotton'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
