# Generated by Django 4.2.7 on 2025-09-25 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_weigth_unit_productvariant_weight_unit'),
        ('orders', '0003_remove_orderitem_loose'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='loose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.loose'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant'),
        ),
    ]
