# Generated by Django 5.2.6 on 2025-09-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_voice_order',
            field=models.BooleanField(default=False),
        ),
    ]
