# Generated by Django 5.2.6 on 2025-09-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_accuracy_order_latitude_order_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_pdf',
            field=models.FileField(blank=True, null=True, upload_to='order_pdfs/'),
        ),
    ]
