# Generated by Django 4.2.7 on 2025-09-24 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=200)),
                ('shop_address', models.CharField(blank=True, max_length=300, null=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20)),
                ('owner_name', models.CharField(blank=True, max_length=150, null=True)),
                ('owner_phone', models.CharField(max_length=20)),
                ('is_whatsapp', models.BooleanField(default=True)),
                ('shop_image', models.ImageField(blank=True, null=True, upload_to='media/shop')),
                ('status', models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='open', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='plants_mall_shops.category')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_man_shops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius_meters', models.FloatField(default=5000.0, help_text='Radius in meters to show nearby shops')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=200, unique=True)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_tracker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopVoiceNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_note', models.FileField(upload_to='media/shops_register_voice_note')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_notes', to='plants_mall_shops.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/shops_images')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='plants_mall_shops.shop')),
            ],
        ),
    ]
