# Generated by Django 5.2.6 on 2025-09-10 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('voice_note_for_shop_name', models.FileField(blank=True, null=True, upload_to='media/shop_voice_notes/')),
                ('voice_note_for_category', models.FileField(blank=True, null=True, upload_to='media/shop_voice_notes/')),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20)),
                ('voice_note_for_size', models.FileField(blank=True, null=True, upload_to='media/shop_voice_notes/')),
                ('owner_name', models.CharField(blank=True, max_length=150, null=True)),
                ('voice_note_owner_name', models.FileField(blank=True, null=True, upload_to='media/shop_voice_notes/')),
                ('owner_phone', models.CharField(max_length=20, unique=True)),
                ('voice_note_for_owner_phone', models.FileField(blank=True, null=True, upload_to='media/shop_voice_notes/')),
                ('shop_image', models.ImageField(blank=True, null=True, upload_to='media/shop')),
                ('status', models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='open')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, unique=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, unique=True)),
                ('accuracy', models.DecimalField(decimal_places=6, max_digits=9, unique=True)),
                ('voice_note', models.FileField(blank=True, null=True, upload_to='media/shop_voice_notes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='plants_mall_shops.category')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_man_shops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/shops_images')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='plants_mall_shops.shop')),
            ],
        ),
    ]
