# Generated by Django 4.2.7 on 2025-09-24 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants_mall_shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/shops_images')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_images', to='plants_mall_shops.shop')),
            ],
        ),
    ]
