# Generated by Django 5.2.6 on 2025-09-10 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_mall_shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='voice_note',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='voice_note_for_category',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='voice_note_for_owner_phone',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='voice_note_for_shop_name',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='voice_note_for_size',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='voice_note_owner_name',
        ),
        migrations.CreateModel(
            name='ShopVoiceNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_note', models.FileField(upload_to='media/shops_register_voice_note')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_voice_note', to='plants_mall_shops.shop')),
            ],
        ),
    ]
