# Generated by Django 5.2.6 on 2025-09-10 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_mall_shops', '0002_remove_shop_voice_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopvoicenotes',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_notes', to='plants_mall_shops.shop'),
        ),
    ]
