# Generated by Django 5.2.6 on 2025-09-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_mall_shops', '0003_alter_shopvoicenotes_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
