# Generated by Django 5.2.6 on 2025-09-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_mall_shops', '0004_shop_shop_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius_meters', models.FloatField(default=5000.0, help_text='Radius in meters to show nearby shops')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
