# Generated by Django 5.2.6 on 2025-09-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_mall_shops', '0005_shopsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='accuracy',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='shop',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='shop',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner_phone',
            field=models.CharField(max_length=20),
        ),
    ]
