# Generated by Django 5.2.6 on 2025-09-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_mall_shops', '0006_alter_shop_accuracy_alter_shop_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='accuracy',
            field=models.DecimalField(decimal_places=9, max_digits=9),
        ),
        migrations.AlterField(
            model_name='shop',
            name='latitude',
            field=models.DecimalField(decimal_places=9, max_digits=9),
        ),
        migrations.AlterField(
            model_name='shop',
            name='longitude',
            field=models.DecimalField(decimal_places=9, max_digits=9),
        ),
    ]
