# Generated by Django 4.2.7 on 2025-09-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_mall_shops', '0011_alter_stafflocations_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='open', max_length=100),
        ),
    ]
