# Generated by Django 4.2.7 on 2025-09-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_mall_shops', '0012_alter_shop_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_whatsapp',
            field=models.BooleanField(default=True),
        ),
    ]
