# Generated by Django 5.2.6 on 2025-09-12 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing_unit', models.CharField(help_text='E.g., 250kg, 500kg', max_length=50)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='products/barcodes/')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cotton', to='products.product')),
            ],
        ),
    ]
