# Generated by Django 5.2.6 on 2025-09-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cotton'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotton',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cotton',
            name='packing_unit',
            field=models.CharField(help_text='E.g., 2kg, 500gm', max_length=50),
        ),
        migrations.AlterField(
            model_name='cotton',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
