# Generated by Django 5.2.6 on 2025-09-12 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cotton_barcode_number_alter_cotton_packing_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotton',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cottons', to='products.product'),
        ),
    ]
