# Generated by Django 4.2.7 on 2025-09-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_packing_unit_productvariant_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='weigth_unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml')], default='g', help_text='e.g. 250g, 500g, 1kg', max_length=100),
        ),
    ]
