# Generated by Django 4.2.7 on 2025-09-24 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productvariant_weigth_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotton',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartons', to='products.productvariant'),
        ),
    ]
