# Generated by Django 4.2.7 on 2025-09-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_cotton_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotton',
            name='discount_value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
