# Generated by Django 4.2.7 on 2025-09-24 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_cotton_discount_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loose',
            old_name='discount_price',
            new_name='discount_value',
        ),
    ]
