# Generated by Django 5.2.6 on 2025-09-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_cotton_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotton',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
