# Generated by Django 4.2.7 on 2025-09-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_discount_price_loose_discount_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotton',
            name='no_of_cartons',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cotton',
            name='pieces_per_carton',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
