# Generated by Django 5.2.6 on 2025-09-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_cotton_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotton',
            name='sold_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
