# Generated by Django 4.2.7 on 2025-09-25 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_cotton_no_of_cartons_cotton_pieces_per_carton'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='weigth_unit',
            new_name='weight_unit',
        ),
    ]
