# Generated by Django 4.2.7 on 2025-09-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_weigth_unit_productvariant_weight_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='weight_unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('ltr', 'ltr')], default='g', help_text='e.g. g, g, kg', max_length=100),
        ),
    ]
