# Generated by Django 4.2.7 on 2025-09-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productvariant_weight_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotton',
            old_name='no_of_cartons',
            new_name='no_of_cartons_history',
        ),
        migrations.AddField(
            model_name='cotton',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
