# Generated by Django 4.2.7 on 2025-09-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_no_of_cartons_cotton_no_of_cartons_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='in_stcok',
            field=models.BooleanField(default=True),
        ),
    ]
