# Generated by Django 4.2.7 on 2025-09-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productvariant_in_stcok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='in_stcok',
        ),
        migrations.AddField(
            model_name='cotton',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loose',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
